server {
	listen 98 default_server;
	listen [::]:98 default_server;

	root /var/www/puntopago/public;
	index index.php;
	server_name _;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/run/php/php8.3-fpm.sock;
	}

	location ~ /\.(?!well-known).* {
		deny all;
	}
}
